"""users

Revision ID: 1b4e1b080bf8
Revises: 2fd7b512efa0
Create Date: 2021-04-01 13:58:57.476501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4e1b080bf8'
down_revision = '2fd7b512efa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
